// lib/doctorsData.js

export const doctors = [
  {
    name: "Dr. Richard Jones",
    email: "richard.jones@example.com",
    password: "password123", // Remember to hash passwords in a real application!
    image: "/images/doc1.png",
    speciality: "General physician",
    degree: "MD, General Medicine",
    experience: "12 years",
    about:
      "A dedicated general physician with over a decade of experience in primary care and patient management.",
    available: true,
    fees: 15000,
    address: { street: "123 Allen Avenue", city: "Ikeja", state: "Lagos" },
    date: Date.now(),
  },
  {
    name: "Dr. Emily Larson",
    email: "emily.larson@example.com",
    password: "password123",
    image: "/images/doc2.png",
    speciality: "Gynecologist",
    degree: "MBBS, DGO",
    experience: "8 years",
    about:
      "Specializes in women's reproductive health, providing compassionate and comprehensive care.",
    available: true,
    fees: 20000,
    address: {
      street: "456 Ozumba Mbadiwe Ave",
      city: "Victoria Island",
      state: "Lagos",
    },
    date: Date.now(),
  },
  {
    name: "Dr. Sarah Patel",
    email: "sarah.patel@example.com",
    password: "password123",
    image: "/images/doc3.png",
    speciality: "Dermatologist",
    degree: "MD, Dermatology",
    experience: "10 years",
    about:
      "Expert in treating skin, hair, and nail conditions with a focus on cosmetic and medical dermatology.",
    available: true,
    fees: 18000,
    address: { street: "789 Admiralty Way", city: "Lekki", state: "Lagos" },
    date: Date.now(),
  },
  {
    name: "Dr. Christopher Lee",
    email: "christopher.lee@example.com",
    password: "password123",
    image: "/images/doc4.png",
    speciality: "Pediatricians",
    degree: "MBBS, DCH",
    experience: "15 years",
    about:
      "Passionate about children's health, providing care for infants, children, and adolescents.",
    available: true,
    fees: 12000,
    address: { street: "101 Bourdillon Road", city: "Ikoyi", state: "Lagos" },
    date: Date.now(),
  },
  {
    name: "Dr. Jennifer Garcia",
    email: "jennifer.garcia@example.com",
    password: "password123",
    image: "/images/doc5.png",
    speciality: "Neurologist",
    degree: "MD, Neurology",
    experience: "9 years",
    about:
      "Focuses on the diagnosis and treatment of disorders of the nervous system.",
    available: true,
    fees: 25000,
    address: {
      street: "212 Herbert Macaulay Way",
      city: "Yaba",
      state: "Lagos",
    },
    date: Date.now(),
  },
  {
    name: "Dr. Andrew Williams",
    email: "andrew.williams@example.com",
    password: "password123",
    image: "/images/doc6.png",
    speciality: "Gastroenterologist",
    degree: "MD, Gastroenterology",
    experience: "11 years",
    about:
      "Specializes in the management of diseases of the gastrointestinal tract and liver.",
    available: true,
    fees: 22000,
    address: {
      street: "333 Funsho Williams Avenue",
      city: "Surulere",
      state: "Lagos",
    },
    date: Date.now(),
  },
  {
    name: "Dr. Christopher Davis",
    email: "christopher.davis@example.com",
    password: "password123",
    image: "/images/doc7.png",
    speciality: "General physician",
    degree: "MD, General Medicine",
    experience: "7 years",
    about:
      "Provides comprehensive medical care to patients of all ages, with a focus on preventive care.",
    available: true,
    fees: 14000,
    address: {
      street: "444 Obafemi Awolowo Way",
      city: "Ikeja",
      state: "Lagos",
    },
    date: Date.now(),
  },
  {
    name: "Dr. Timothy White",
    email: "timothy.white@example.com",
    password: "password123",
    image: "/images/doc8.png",
    speciality: "Gynecologist",
    degree: "MBBS, DGO",
    experience: "14 years",
    about:
      "Experienced gynecologist dedicated to providing personalized care for women's health issues.",
    available: true,
    fees: 21000,
    address: {
      street: "555 Adeola Odeku Street",
      city: "Victoria Island",
      state: "Lagos",
    },
    date: Date.now(),
  },
  {
    name: "Dr. Ava Mitchell",
    email: "ava.mitchell@example.com",
    password: "password123",
    image: "/images/doc9.png",
    speciality: "Dermatologist",
    degree: "MD, Dermatology",
    experience: "6 years",
    about:
      "Specializes in modern dermatological treatments and cosmetic procedures.",
    available: true,
    fees: 19000,
    address: { street: "666 Freedom Way", city: "Lekki", state: "Lagos" },
    date: Date.now(),
  },
  {
    name: "Dr. Jeffrey King",
    email: "jeffrey.king@example.com",
    password: "password123",
    image: "/images/doc10.png",
    speciality: "Pediatricians",
    degree: "MBBS, DCH",
    experience: "10 years",
    about:
      "A friendly and approachable pediatricians committed to the well-being of children.",
    available: true,
    fees: 13000,
    address: { street: "777 Glover Road", city: "Ikoyi", state: "Lagos" },
    date: Date.now(),
  },
  {
    name: "Dr. Zoe Kelly",
    email: "zoe.kelly@example.com",
    password: "password123",
    image: "/images/doc11.png",
    speciality: "Neurologist",
    degree: "MD, Neurology",
    experience: "7 years",
    about:
      "Skilled in diagnosing and managing complex neurological conditions.",
    available: true,
    fees: 26000,
    address: { street: "888 Commercial Avenue", city: "Yaba", state: "Lagos" },
    date: Date.now(),
  },
  {
    name: "Dr. Patrick Harris",
    email: "patrick.harris@example.com",
    password: "password123",
    image: "/images/doc12.png",
    speciality: "Gastroenterologist",
    degree: "MD, Gastroenterology",
    experience: "9 years",
    about:
      "Provides expert care for a wide range of digestive system disorders.",
    available: true,
    fees: 23000,
    address: {
      street: "999 Bode Thomas Street",
      city: "Surulere",
      state: "Lagos",
    },
    date: Date.now(),
  },
  {
    name: "Dr. Chloe Evans",
    email: "chloe.evans@example.com",
    password: "password123",
    image: "/images/doc13.png",
    speciality: "General physician",
    degree: "MD, General Medicine",
    experience: "5 years",
    about:
      "A caring general physician focused on holistic patient wellness and disease prevention.",
    available: true,
    fees: 13500,
    address: { street: "111 Opebi Road", city: "Ikeja", state: "Lagos" },
    date: Date.now(),
  },
  {
    name: "Dr. Ryan Martinez",
    email: "ryan.martinez@example.com",
    password: "password123",
    image: "/images/doc14.png",
    speciality: "Dermatologist",
    degree: "MD, Dermatology",
    experience: "8 years",
    about:
      "Expert in clinical dermatology and aesthetic treatments for healthy skin.",
    available: true,
    fees: 20000,
    address: { street: "222 Fola Osibo Street", city: "Lekki", state: "Lagos" },
    date: Date.now(),
  },
  {
    name: "Dr. Amelia Hill",
    email: "amelia.hill@example.com",
    password: "password123",
    image: "/images/doc15.png",
    speciality: "Dermatologist",
    degree: "MBBS, Dip. Derm",
    experience: "9 years",
    about:
      "Dedicated to providing top-quality dermatological care and patient education.",
    available: true,
    fees: 18500,
    address: { street: "333 Agungi Lekki", city: "Lekki", state: "Lagos" },
    date: Date.now(),
  },
  // {
  //   name: "Dr. Samuel Adeoye",
  //   email: "samuel.adeoye@example.com",
  //   password: "password123",
  //   image: "/doc16.png",
  //   speciality: "Pediatricians",
  //   degree: "MD, Pediatrics",
  //   experience: "8 years",
  //   about:
  //     "A compassionate pediatricians dedicated to providing exceptional care for children from infancy through adolescence.",
  //   available: true,
  //   fees: 13500,
  //   address: { street: "15 Shitta Street", city: "Surulere", state: "Lagos" },
  //   date: Date.now(),
  // },
  // {
  //   name: "Dr. Funke Bello",
  //   email: "funke.bello@example.com",
  //   password: "password123",
  //   image: "/doc17.png",
  //   speciality: "Pediatricians",
  //   degree: "MBBS, DCH",
  //   experience: "12 years",
  //   about:
  //     "Specializes in developmental pediatrics and adolescent health, ensuring a healthy future for every child.",
  //   available: true,
  //   fees: 15000,
  //   address: { street: "48 Opebi Road", city: "Ikeja", state: "Lagos" },
  //   date: Date.now(),
  // },
  // {
  //   name: "Dr. Chinwe Okoro",
  //   email: "chinwe.okoro@example.com",
  //   password: "password123",
  //   image: "/doc18.png",
  //   speciality: "Pediatricians",
  //   degree: "MD, FAAP",
  //   experience: "7 years",
  //   about:
  //     "Focused on preventive care and building strong, healthy families through expert pediatric guidance.",
  //   available: true,
  //   fees: 12500,
  //   address: { street: "10B Fola Osibo Street", city: "Lekki", state: "Lagos" },
  //   date: Date.now(),
  // },
];
